Repository bruce-gordon/whats-cookin, pull requests merged in 2020-10, with the labels that each got.

#16 Feature initial buildout
  assets/icons/001-bookmark.svg
  assets/icons/002-magnifying-glass.svg
  assets/icons/003-cooking-pots.svg
  assets/icons/004-whisk.svg
  index.html
  src/Ingredient.js
  src/Recipe.js
  src/User.js
  src/index.html
  styles.css
  test/Ingredient-test.js
  test/Recipe-test.js
  test/User-test.js
Labels: enhancement

#19 Feature ingredient and recipe classes
  src/Ingredient.js
  src/Pantry.js
  src/Recipe.js
  test/Ingredient-test.js
  test/Pantry-test.js
  test/Recipe-test.js
Labels: enhancement

#20 Feature/user and test buildout
  package-lock.json
  src/User.js
  test/User-test.js
  test/dummy-data/testRecipes.js
  test/dummy-data/testUsers.js
Labels: User class, bug, enhancement

#21 Feature user methods pantry
  src/User.js
  test/User-test.js
Labels: enhancement

#35 Feature dom buildout
  index.html
  src/Ingredient.js
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/scripts.js
  styles.css
  test/User-test.js
Labels: enhancement

#36 Feature/wrap user initial css
  assets/priscilla-du-preez-W8F9kM7F-5U-unsplash.jpg
  index.html
  src/Ingredient.js
  src/Pantry.js
  src/User.js
  styles.css
  test/User-test.js
Labels: css, enhancement

#37 Feature search and recipe views
  src/scripts.js
Labels: enhancement

#38 Featue/category view css
  assets/icons/001-bookmark.svg
  assets/icons/bookmark.svg
  assets/priscilla-du-preez-W8F9kM7F-5U-unsplash.jpg
  index.html
  src/scripts.js
  styles.css
Labels: enhancement

#39 Feature individual recipe view
  data/recipes.js
  index.html
  src/Recipe.js
  src/scripts.js
  test/Recipe-test.js
Labels: enhancement

#42 Feature favorite recipe view
  data/recipes.js
  src/User.js
  src/scripts.js
  styles.css
Labels: enhancement

#43 Feature/home view css
  assets/apple.jpg
  assets/header-img.jpg
  assets/icons/gloves.svg
  assets/spices-556x370.jpg
  index.html
  src/scripts.js
  styles.css
Labels: css, enhancement

#47 Feature/recipe view styling
  index.html
  src/scripts.js
  styles.css
Labels: css, enhancement

#49 Update README.md
  README.md
Labels: documentation

#50 Refactor app
  src/Ingredient.js
  src/Pantry.js
  src/Recipe.js
  src/User.js
  src/scripts.js
  test/Recipe-test.js
  test/User-test.js
Labels: enhancement

#51 Feature/recipe view review
  index.html
  styles.css
Labels: css, enhancement
